name: update_dispatch

on:
  repository_dispatch:
    types: [release-flame]


jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: update docs site
        run: ./scripts/update-docs.sh
      - name: Commit report
        run: |
          git config --global user.name 'Auto update'
          git config --global user.email 'renancaraujo@users.noreply.github.com'
          git commit -am "Updated site"
          git push
